CC=gcc
CFLAGS=-Wall
LDFLAGS=-lX11

all: xtut1 xtut2 xtut3 xtut5 xtut6 xtut7 xtut8 xtut9

clean:
	find . -perm +100 -type f -delete

xtut1: xtut1.c

xtut2: xtut2.c

xtut3: xtut3.c

xtut5: xtut5.c

xtut6: xtut6.c

xtut7: xtut7.c

xtut8: xtut8.c

xtut9: xtut9.c
